// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Analyze(arg1:string,arg2:main.AnalysisOptions):Promise<main.AnalysisResult>;

export function Export(arg1:string,arg2:main.AnalysisOptions):Promise<Array<string>>;

export function OpenFileDialog():Promise<string>;

export function ResolveIP(arg1:string):Promise<string>;
